### ISSUE TITLE
Rename Package

### ISSUE THREAD

**Issue by ChristopheCVB** [obs-websocket-community-projects/websocket-obs-java#72]
Rename Package to `io.obswebsocket.client`?

**Comment by TinaTiel** [comment]
So we'd have a groupId of `io.obswebsocket.client` and artifactId of `obsremotejava`?

What if instead we had `io.obswebsocket` as groupId and `javaclient` as artifactId instead?

**Comment by ChristopheCVB** [comment]
> What if instead we had io.obswebsocket as groupId and javaclient as artifactId instead?
That was indeed the idea

**Comment by TinaTiel** [comment]
Shall we close this and move to a discussion?
